sudo: required
services:
  - docker
language: nodejs
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

env:
  matrix:
    - BUILD=alpine CROSSARCH_USE_MULTIARCH_ALPINE=true CROSSARCH_BUILD_IS_SEMVER=false CROSSARCH_BUILD_SQUASH=false
    - BUILD=caddy
    - BUILD=home-assistant
    - BUILD=mosquitto
    - BUILD=node
install:
  - set -eo pipefail
  - npm install
script:
  - set -eo pipefail
  - |
    node ./index.js
