sudo: required
services:
  - docker
language: node_js
node_js:
  - "8"
cache: yarn

env:
  global:
    - FORCE_COLOR=true
  matrix:
    - BUILD=alpine
    - BUILD=caddy
    - BUILD=home-assistant
    - BUILD=mosquitto
    - BUILD=node
    - BUILD=ngrok

install:
  - yarn
script:
  - node ./index.js
