sudo: required
services:
  - docker
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

env:
  matrix:
    - BUILD=alpine
    - BUILD=caddy
    - BUILD=home-assistant
    - BUILD=mosquitto
    - BUILD=node
script:
  - node ./index.js
