RUN echo "http://nl.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
 && echo "http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
 && apk upgrade --no-cache --available
